#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill ~/Pictures/wallpapers/mikael-gustafsson-amongtrees-2-8.jpg &
sh ~/.config/polybar/launch.sh &

# Workspaces
bspc monitor -d I II III IV V VI VII

# Other stuff
bspc config border_width	0
bspc config window_gap		12
bspc config split_ratio		0.5
bspc config top_padding		25
